apiVersion: v1
kind: Service
metadata:
  name: {{ include "shepherd.componentName" (dict "root" . "component" "server") }}
  namespace: {{ include "shepherd.namespace" . }}
  labels:
    {{- include "shepherd.componentLabels" (dict "root" . "component" "server") | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "shepherd.componentSelectorLabels" (dict "root" . "component" "server") | nindent 4 }}
