{{- if .Values.observability.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "shepherd.componentName" (dict "root" . "component" "server") }}
  namespace: {{ default (include "shepherd.namespace" .) .Values.observability.serviceMonitor.namespace }}
  labels:
    {{- include "shepherd.componentLabels" (dict "root" . "component" "monitoring") | nindent 4 }}
    {{- with .Values.observability.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.observability.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "shepherd.componentSelectorLabels" (dict "root" . "component" "server") | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ include "shepherd.namespace" . | quote }}
  {{- with .Values.observability.serviceMonitor.jobLabel }}
  jobLabel: {{ . | quote }}
  {{- end }}
  endpoints:
    - port: http
      path: {{ .Values.observability.metrics.path | quote }}
      interval: {{ .Values.observability.serviceMonitor.interval | quote }}
      scheme: {{ .Values.observability.serviceMonitor.scheme | quote }}
      {{- with .Values.observability.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . | quote }}
      {{- end }}
{{- end -}}
